### ISSUE TITLE
Compile exits with error

### ISSUE THREAD

**Issue by inf265** [telekom/mp-dccp#1]
When following the build procedure, the kernel does not build.
Local: 5.4.0-66-generic, headers installed.

```✘-2 ~/customers/dtag/mp-dccp [master|✔] 
11:59 $ make -j 4 bindeb-pkg
  CHK     include/config/kernel.release
make KBUILD_SRC=
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  DESCEND  objtool
  CHK     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTCC  scripts/selinux/mdp/mdp
In file included from scripts/selinux/genheaders/genheaders.c:19:
./security/selinux/include/classmap.h:245:2: error: #error New address family defined, please update secclass_map.
  245 | #error New address family defined, please update secclass_map.
      |  ^~~~~
make[5]: *** [scripts/Makefile.host:102: scripts/selinux/genheaders/genheaders] Error 1
make[4]: *** [scripts/Makefile.build:585: scripts/selinux/genheaders] Error 2
make[4]: *** Waiting for unfinished jobs....
In file included from scripts/selinux/mdp/mdp.c:49:
./security/selinux/include/classmap.h:245:2: error: #error New address family defined, please update secclass_map.
  245 | #error New address family defined, please update secclass_map.
      |  ^~~~~
make[5]: *** [scripts/Makefile.host:102: scripts/selinux/mdp/mdp] Error 1
make[4]: *** [scripts/Makefile.build:585: scripts/selinux/mdp] Error 2
make[3]: *** [scripts/Makefile.build:585: scripts/selinux] Error 2
make[3]: *** Waiting for unfinished jobs....
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
make[2]: *** [Makefile:572: scripts] Error 2
make[1]: *** [scripts/package/Makefile:91: bindeb-pkg] Error 2
make: *** [Makefile:1374: bindeb-pkg] Error 2
✘-2 ~/customers/dtag/mp-dccp [master|✔]```

**Comment by markusa** [comment]
Hi @inf265,

first my apologies, we haven't make clear in which environment it's save to compile our Kernel at https://github.com/telekom/mp-dccp/commit/d9b4b7471a69184105885abbc4d45c011b82543d. We will add the prerequisites soon to https://multipath-dccp.org/compile_install.html.

Independent from that, I think I can provide you a way to compile this under more recent Ubuntu versions.

The error which stopps you from compiling is related to the SELinux extension and fixed with
[1.patch.txt](https://github.com/telekom/mp-dccp/files/6123740/1.patch.txt)
 from https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=760f8522ce08

Probably in a later step you will stumble over another error, related to the usage of a gcc version >8 in combination with retpoline fixes which says `-mindirect-branch and -fcf-protection are not compatible`
[2.patch.txt](https://github.com/telekom/mp-dccp/files/6123758/2.patch.txt)
from https://patchwork.kernel.org/project/linux-kbuild/patch/20190709184919.20178-1-seth.forshee@canonical.com/ will fix this.

It would be great if you can provide feedback.

**Comment by inf265** [comment]
Thx that worked for me.
