### ISSUE TITLE
Can't compile the kernel (bindeb-pkg)

### ISSUE THREAD

**Issue by PedroRocha9** [telekom/mp-dccp#38]
Hey, everyone, I need some help.

When following [this compile&install tutorial](https://multipath-dccp.org/compile_install.html), I've stumbled upon an error on the ```bash sudo make -j <nr_processors> bindeb-pkg``` step.
The output of the command is 1688 lines long, therefore I didn't put it here, however, I can attach it as a .txt file.

In terms of requirements and versions of several installed libraries, I've 
[MP-DCCP_Setup.md](https://github.com/telekom/mp-dccp/files/10289216/MP-DCCP_Setup.md)
made a markdown file (attached) to keep track of the installation process.

But, from what I saw on other issues (and sorry if there's one answer to this problem already, however I couldn't find it), the main questions about system versions the answered bellow.

- Ubuntu 21.04
- Kernel Version: 5.10.130-0510130-generic
- gcc version 10.3.0 (Ub
untu 10.3.0-1ubuntu1)
- ncurses-devel<br>
    ```bash
    sudo apt-get install libncurses5-dev libncursesw5-dev
   ```
  
For further detail you may answer or check some of the steps I've made to this point, in this markdown file:
[MP-DCCP_Setup.md](https://github.com/telekom/mp-dccp/files/10289222/MP-DCCP_Setup.md)

**Comment by pawelsikora** [comment]
Could you share the .txt file with the command output?

I had some issues with **bindeb**-pkg on my environment (Ubuntu **22.04**) too.
In my case it was caused by an empty **arch/x86/entry/thunk_64.o** object file.

Have a look at:
[https://github.com/containers/libkrunfw/issues/4](https://github.com/containers/libkrunfw/issues/4)
(patch from above mentioned link in an attachment. Please confirm if this patch is applying correctly - 
in my case I needed to do it manually)

[3.patch.txt](https://github.com/telekom/mp-dccp/files/10316630/3.patch.txt)
